Feature/style et composant
Natchii59/ozepi pull request #25
Opened 2024-06-26 12:07 UTC by Benjaminkli

installation et config de nativewind 

installation de nativewind: 2.0.11
installation de tailwindcss: 3.3.2 (les version au dessus ne fonctionne pas avec nativewind d'après la doc)
ajout du plugin dans le babel.config.js

[doc](https://www.nativewind.dev/quick-starts/expo)

2024-06-26 13:29 UTC, GeoffH02 requested changes

2024-06-26 13:29 UTC, GeoffH02 commented on apps/application/tailwind.config.js
> +  content: ["./App.{js,jsx,ts,tsx}", "./<custom directory>/**/*.{js,jsx,ts,tsx}"],
Change pour le bon directory

2024-06-26 13:31 UTC, GeoffH02 requested changes

2024-06-26 13:31 UTC, GeoffH02 commented on apps/application/babel.config.js
> +    plugins: ["nativewind/babel"],
Et des simples quotes ici

2024-07-01 07:37 UTC, ogmogetch approved these changes

2024-07-01 08:36 UTC, GeoffH02 approved these changes

2024-07-01 08:36 UTC, merged